version: '3.8'
services:
  jenkins:
    image: custom-jenkins-with-maven  # Use your custom image
    container_name: jenkins-custom-with-maven
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /home/cristian/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker
      - /home/cristian/eclipse-selenium/my_qa_framework:/var/jenkins_home/workspace/my_qa_framework